// "Data Types in JavaScript"

// Primitive data types in JavaScript include:

// -Strings - Any data under single quote, double quote or backtick quote
// -Numbers - Integers, floats
// -Booleans - true or false value
// -Undefined - a declared variable without a value
// -Null - empty value or no value
// -Symbol - A unique value that can be generated by Symbol constructor

//////////////////////////////

// String
let fullName = "Emre Erden";
console.log(fullName); // Output: Emre Erden

// Number
let age = 22;
console.log(age); // Output: 25

// Boolean
let isMarried = false;
console.log(isMarried); // Output: false

// Undefined
let car;
console.log(car); // Output: undefined

// Null
let house = null;
console.log(house); // Output: null

// Array
let fruits = ["apple", "banana", "orange"];
console.log(fruits); // Output: ["apple", "banana", "orange"]

// Object
const person = {
  fullName: "Emre Erden",
  age: 22,
  isMarried: false,
};
console.log(person); // Output: {fullName: "Emre Erden", age: 22, isMarried: false}

///////////////

// Primitive data types are immutable(non-modifiable) data types. Once a primitive data type is created we cannot modify it.

let word = "JavaScript";
word[0] = "Y";
console.log(word); // Output: JavaScript

///////////////

// Primitive data types are compared by its values.

let num1 = 3;
let num2 = 3;
console.log(num1 == num2); // Output: true

let js = "JavaScript";
let py = "Python";
console.log(js == py); // Output: false

let lightOn = true;
let lightOff = false;
console.log(lightOn == lightOff); // Output: false
